/* Generated By:JavaCC: Do not edit this line. PlinguaJavaCcParserConstants.java */
package org.gcn.plinguacore.parser.input.plingua;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PlinguaJavaCcParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MULTISET = 8;
  /** RegularExpression Id. */
  int FIRST_MULTISET = 9;
  /** RegularExpression Id. */
  int SECOND_MULTISET = 10;
  /** RegularExpression Id. */
  int INFENV_MULTISET = 11;
  /** RegularExpression Id. */
  int DEF = 12;
  /** RegularExpression Id. */
  int CALL = 13;
  /** RegularExpression Id. */
  int LET = 14;
  /** RegularExpression Id. */
  int MU = 15;
  /** RegularExpression Id. */
  int MEMB_IN = 16;
  /** RegularExpression Id. */
  int MEMB_OUT = 17;
  /** RegularExpression Id. */
  int LOG = 18;
  /** RegularExpression Id. */
  int COS = 19;
  /** RegularExpression Id. */
  int SIN = 20;
  /** RegularExpression Id. */
  int FLOOR = 21;
  /** RegularExpression Id. */
  int MAX0 = 22;
  /** RegularExpression Id. */
  int CEIL = 23;
  /** RegularExpression Id. */
  int ROUND = 24;
  /** RegularExpression Id. */
  int DISSOLVES = 25;
  /** RegularExpression Id. */
  int VARIANT = 26;
  /** RegularExpression Id. */
  int DEBUG = 27;
  /** RegularExpression Id. */
  int MARCS = 28;
  /** RegularExpression Id. */
  int MDICT = 29;
  /** RegularExpression Id. */
  int MINST = 30;
  /** RegularExpression Id. */
  int MSEQ = 31;
  /** RegularExpression Id. */
  int MASYNCH = 32;
  /** RegularExpression Id. */
  int MVALID = 33;
  /** RegularExpression Id. */
  int GUARD = 34;
  /** RegularExpression Id. */
  int STRING = 35;
  /** RegularExpression Id. */
  int ID = 36;
  /** RegularExpression Id. */
  int DOLLAR = 37;
  /** RegularExpression Id. */
  int QUOTE = 38;
  /** RegularExpression Id. */
  int ARROW = 39;
  /** RegularExpression Id. */
  int DOUBLE_ARROW = 40;
  /** RegularExpression Id. */
  int RELABELLING_ARROW = 41;
  /** RegularExpression Id. */
  int UNLINKING_ARROW = 42;
  /** RegularExpression Id. */
  int DOT = 43;
  /** RegularExpression Id. */
  int NATURAL_NUMBER = 44;
  /** RegularExpression Id. */
  int NUMBER = 45;
  /** RegularExpression Id. */
  int PI = 46;
  /** RegularExpression Id. */
  int EMPTY = 47;
  /** RegularExpression Id. */
  int QUESTION = 48;
  /** RegularExpression Id. */
  int AMPERSAND = 49;
  /** RegularExpression Id. */
  int BAR = 50;
  /** RegularExpression Id. */
  int SEPARATOR = 51;
  /** RegularExpression Id. */
  int LBRACE = 52;
  /** RegularExpression Id. */
  int RBRACE = 53;
  /** RegularExpression Id. */
  int COMMA = 54;
  /** RegularExpression Id. */
  int LSQUARE = 55;
  /** RegularExpression Id. */
  int RSQUARE = 56;
  /** RegularExpression Id. */
  int LPAR = 57;
  /** RegularExpression Id. */
  int RPAR = 58;
  /** RegularExpression Id. */
  int COLON = 59;
  /** RegularExpression Id. */
  int DOUBLE_COLON = 60;
  /** RegularExpression Id. */
  int PLUS = 61;
  /** RegularExpression Id. */
  int MINUS = 62;
  /** RegularExpression Id. */
  int MUL = 63;
  /** RegularExpression Id. */
  int DIV = 64;
  /** RegularExpression Id. */
  int MOD = 65;
  /** RegularExpression Id. */
  int INTDIV = 66;
  /** RegularExpression Id. */
  int POW = 67;
  /** RegularExpression Id. */
  int ASIG = 68;
  /** RegularExpression Id. */
  int LESS_THAN = 69;
  /** RegularExpression Id. */
  int GREATER_THAN = 70;
  /** RegularExpression Id. */
  int LESS_OR_EQUAL_THAN = 71;
  /** RegularExpression Id. */
  int GREATER_OR_EQUAL_THAN = 72;
  /** RegularExpression Id. */
  int DIFF = 73;
  /** RegularExpression Id. */
  int INC = 74;
  /** RegularExpression Id. */
  int ICL = 75;
  /** RegularExpression Id. */
  int AND = 76;
  /** RegularExpression Id. */
  int OR = 77;
  /** RegularExpression Id. */
  int STRING_OBJECT = 78;
  /** RegularExpression Id. */
  int MOUTRES_BINARY = 79;
  /** RegularExpression Id. */
  int MOUTRES_NATURAL = 80;
  /** RegularExpression Id. */
  int MOUTRES_SUMMATORIES = 81;
  /** RegularExpression Id. */
  int MASTF = 82;
  /** RegularExpression Id. */
  int MASTH = 83;
  /** RegularExpression Id. */
  int MASTFUNC = 84;
  /** RegularExpression Id. */
  int PROPERTY = 85;
  /** RegularExpression Id. */
  int DUMMY = 86;
  /** RegularExpression Id. */
  int MBOUNDALL = 87;
  /** RegularExpression Id. */
  int MLOCSET = 88;
  /** RegularExpression Id. */
  int FVARIANT = 89;
  /** RegularExpression Id. */
  int FRULE = 90;
  /** RegularExpression Id. */
  int FP_IN = 91;
  /** RegularExpression Id. */
  int FP_OUT = 92;
  /** RegularExpression Id. */
  int FAND = 93;
  /** RegularExpression Id. */
  int FOR = 94;
  /** RegularExpression Id. */
  int PARALLEL = 95;
  /** RegularExpression Id. */
  int FWEIGHT = 96;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"@ms\"",
    "\"@ms1\"",
    "\"@ms2\"",
    "\"@msInfEnv\"",
    "\"def\"",
    "\"call\"",
    "\"let\"",
    "\"@mu\"",
    "\"@min\"",
    "\"@mout\"",
    "\"@log\"",
    "\"@cos\"",
    "\"@sin\"",
    "\"@floor\"",
    "\"@max0\"",
    "\"@ceil\"",
    "\"@round\"",
    "\"@d\"",
    "\"@model\"",
    "\"@debug\"",
    "\"@marcs\"",
    "\"@mdict\"",
    "\"@minst\"",
    "\"@mseq\"",
    "\"@masynch\"",
    "\"@mvalid\"",
    "\"@guard\"",
    "<STRING>",
    "<ID>",
    "\"$\"",
    "\"\\\'\"",
    "\"-->\"",
    "\"<-->\"",
    "\"|-->\"",
    "\"-!>\"",
    "\".\"",
    "<NATURAL_NUMBER>",
    "<NUMBER>",
    "\"@pi\"",
    "\"#\"",
    "\"?\"",
    "\"&\"",
    "\"|\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "<DOUBLE_COLON>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"//\"",
    "\"^\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "<LESS_OR_EQUAL_THAN>",
    "<GREATER_OR_EQUAL_THAN>",
    "\"<>\"",
    "\"+=\"",
    "\"*=\"",
    "\"&&\"",
    "\"||\"",
    "<STRING_OBJECT>",
    "\"@moutres_binary\"",
    "\"@moutres_natural\"",
    "\"@moutres_summatories\"",
    "\"@mastf\"",
    "\"@masth\"",
    "\"@mastfunc\"",
    "\"@property\"",
    "\"@dummy\"",
    "\"@mboundall\"",
    "\"@mlocset\"",
    "\"@fvariant\"",
    "\"@frule\"",
    "\"@fpin\"",
    "\"@fpout\"",
    "\"@fand\"",
    "\"@for\"",
    "\"@parallel\"",
    "\"@fweight\"",
  };

}
